version: '3.8'

services:
  app:
    build:
      context: .
    container_name: healthcare_ecommerce_app
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: healthcare_ecommerce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: healthcare_ecommerce
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: healthcare_ecommerce_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
